"""
Session Report API — generate structured or AI-assisted reports for a session.

Routes:
  POST /api/sessions/<id>/report           structured markdown report (no LLM)
  POST /api/sessions/<id>/report/ai        AI-assisted report with LLM executive summary
  GET  /api/sessions/<id>/notes/export     bulk notes zip download
"""

import io
import logging
import time
import zipfile
from datetime import datetime
from flask import Blueprint, jsonify, request, Response, send_file

from server_core.session_flow import load_session_any, append_event
from server_core.singletons import session_store, llm_client as _llm_client, run_history as _run_history

logger = logging.getLogger(__name__)

api_session_reports_bp = Blueprint("session_reports", __name__)


def _bad(msg: str, status: int = 400) -> Response:
  return jsonify({"success": False, "error": msg}), status  # type: ignore[return-value]


def _save_report_to_notes(session_id: str, content: str, base: str, folder: str = "reports") -> str:
  """Save report to notes/<folder>/<base>.md, suffixing to avoid conflicts. Returns saved path."""
  for i in range(20):
    name = base if i == 0 else f"{base}-{i + 1}"
    if not session_store.note_exists(session_id, name, folder):
      ok = session_store.save_note(session_id, name, content, folder)
      if ok:
        return f"notes/{folder}/{name}.md"
      raise RuntimeError(f"Failed to write note {name} in folder {folder}")
  raise RuntimeError("Could not find a free filename after 20 attempts")


# ── Structured report ──────────────────────────────────────────────────────────

@api_session_reports_bp.route("/api/sessions/<session_id>/report", methods=["POST"])
def generate_report(session_id: str):
  """Generate a structured markdown pentest report for the session."""
  try:
    loaded = load_session_any(session_id)
    if not loaded:
      return _bad("Session not found", 404)

    session_data, _state = loaded
    body = request.get_json(force=True) or {}
    include_notes = body.get("include_notes", True)
    include_event_log = body.get("include_event_log", False)
    download = body.get("download", False)
    save_to_notes = body.get("save_to_notes", False)

    report_md = _build_structured_report(session_id, session_data, include_notes, include_event_log)

    append_event(session_id, "report_generated", "Structured report generated", {
      "include_notes": include_notes,
      "include_event_log": include_event_log,
    })

    if download:
      fname = f"{session_id}_report_{int(time.time())}.md"
      return Response(
        report_md,
        mimetype="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
      )

    saved_path: str | None = None
    if save_to_notes:
      base = f"report-structured-{datetime.now().strftime('%Y-%m-%d')}"
      try:
        saved_path = _save_report_to_notes(session_id, report_md, base)
      except Exception as save_err:
        logger.error(f"Failed to auto-save structured report for {session_id}: {save_err}")

    return jsonify({
      "success": True,
      "report": report_md,
      "session_id": session_id,
      "timestamp": datetime.now().isoformat(),
      **({"saved_path": saved_path} if saved_path else {}),
    })
  except Exception as e:
    logger.error(f"Error generating report for {session_id}: {e}")
    return _bad(str(e), 500)


# ── AI-assisted report ─────────────────────────────────────────────────────────

@api_session_reports_bp.route("/api/sessions/<session_id>/report/ai", methods=["POST"])
def generate_ai_report(session_id: str):
  """Generate an AI-assisted report with executive summary via LLM."""
  try:
    if not _llm_client.is_available():
      return _bad("LLM is not available. Configure VRIKA_LLM_PROVIDER and restart the server.", 503)

    loaded = load_session_any(session_id)
    if not loaded:
      return _bad("Session not found", 404)

    session_data, _state = loaded
    body = request.get_json(force=True) or {}
    include_notes = body.get("include_notes", True)
    include_event_log = body.get("include_event_log", False)
    download = body.get("download", False)
    focus = str(body.get("focus", "")).strip()
    save_to_notes = body.get("save_to_notes", False)

    # Build the structured part first
    structured = _build_structured_report(session_id, session_data, include_notes, include_event_log)

    # Ask LLM for executive summary + risk analysis (pass actual tools, not planned)
    actual_tools = _actual_tools_run(session_id, session_data)
    executive_summary = _generate_executive_summary(session_data, focus, actual_tools)

    report_md = f"""# Security Assessment Report — {session_data.get('name') or session_data.get('target', session_id)}

*Generated by NyxStrike AI on {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}*

---

## Executive Summary

{executive_summary}

---

{structured}
"""

    append_event(session_id, "ai_report_generated", "AI-assisted report generated", {
      "include_notes": include_notes,
      "llm_available": True,
    })

    if download:
      fname = f"{session_id}_ai_report_{int(time.time())}.md"
      return Response(
        report_md,
        mimetype="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
      )

    saved_path: str | None = None
    if save_to_notes:
      base = f"report-ai-{datetime.now().strftime('%Y-%m-%d')}"
      try:
        saved_path = _save_report_to_notes(session_id, report_md, base)
      except Exception as save_err:
        logger.error(f"Failed to auto-save AI report for {session_id}: {save_err}")

    return jsonify({
      "success": True,
      "report": report_md,
      "executive_summary": executive_summary,
      "session_id": session_id,
      "ai_generated": True,
      "timestamp": datetime.now().isoformat(),
      **({"saved_path": saved_path} if saved_path else {}),
    })
  except Exception as e:
    logger.error(f"Error generating AI report for {session_id}: {e}")
    return _bad(str(e), 500)


# ── Bulk notes export (zip) ────────────────────────────────────────────────────

@api_session_reports_bp.route("/api/sessions/<session_id>/notes/export", methods=["GET"])
def export_notes_zip(session_id: str):
  """Download all notes for a session as a zip archive."""
  try:
    loaded = load_session_any(session_id)
    if not loaded:
      return _bad("Session not found", 404)

    notes = session_store.list_notes(session_id)
    if not notes:
      return _bad("No notes to export", 404)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
      for note in notes:
        name = note["filename"]
        folder = note.get("folder", "")
        content = session_store.load_note(session_id, name, folder)
        if content is None:
          continue
        arc_path = f"{folder}/{name}.md" if folder else f"{name}.md"
        zf.writestr(arc_path, content)

    buf.seek(0)
    fname = f"{session_id}_notes_{int(time.time())}.zip"
    return send_file(
      buf,
      mimetype="application/zip",
      as_attachment=True,
      download_name=fname,
    )
  except Exception as e:
    logger.error(f"Error exporting notes for {session_id}: {e}")
    return _bad(str(e), 500)


# ── Helpers ────────────────────────────────────────────────────────────────────

def _severity_emoji(sev: str) -> str:
  return {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
  }.get(str(sev).lower(), "⚪")


def _build_structured_report(
  session_id: str,
  session_data: dict,
  include_notes: bool,
  include_event_log: bool,
) -> str:
  """Build a structured markdown report from session data."""
  name = session_data.get("name") or session_data.get("target", session_id)
  target = session_data.get("target", "unknown")
  status = session_data.get("status", "active")
  objective = session_data.get("objective", "")
  risk_level = session_data.get("risk_level", "unknown")
  total_findings = session_data.get("total_findings", 0)
  created_at = session_data.get("created_at", 0)
  updated_at = session_data.get("updated_at", 0)
  tools_executed = _actual_tools_run(session_id, session_data)
  workflow_steps = session_data.get("workflow_steps", [])
  findings = session_data.get("findings", [])
  handover_history = session_data.get("handover_history", [])
  event_log = session_data.get("event_log", [])
  description = session_data.get("description", "")

  lines = []

  # Header
  if not include_event_log:
    # If AI report will add its own top header, start from metadata section
    lines.append(f"# Security Assessment Report — {name}\n")
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}*\n")
    lines.append("")

  # Metadata
  lines.append("## Session Metadata\n")
  lines.append(f"| Field | Value |")
  lines.append(f"|-------|-------|")
  lines.append(f"| Session ID | `{session_id}` |")
  lines.append(f"| Target | `{target}` |")
  lines.append(f"| Status | {status} |")
  lines.append(f"| Risk Level | **{risk_level.upper()}** |")
  lines.append(f"| Total Findings | {total_findings} |")
  if objective:
    lines.append(f"| Objective | {objective} |")
  if description:
    lines.append(f"| Description | {description} |")
  if created_at:
    lines.append(f"| Created | {_fmt_ts(created_at)} |")
  if updated_at:
    lines.append(f"| Last Updated | {_fmt_ts(updated_at)} |")
  lines.append("")

  # Tools executed
  if tools_executed:
    lines.append("## Tools Executed\n")
    unique_tools = []
    seen = set()
    for t in tools_executed:
      if t not in seen:
        seen.add(t)
        unique_tools.append(t)
    for tool in unique_tools:
      lines.append(f"- `{tool}`")
    lines.append("")

  # Findings
  if findings:
    lines.append("## Findings\n")

    # Group by severity
    by_severity = {}
    for f in findings:
      sev = str(f.get("severity", "info")).lower()
      by_severity.setdefault(sev, []).append(f)

    for sev in ("critical", "high", "medium", "low", "info"):
      if sev not in by_severity:
        continue
      emoji = _severity_emoji(sev)
      lines.append(f"### {emoji} {sev.capitalize()} ({len(by_severity[sev])})\n")
      for idx, finding in enumerate(by_severity[sev], 1):
        lines.append(f"#### {idx}. {finding.get('title', 'Untitled Finding')}\n")
        if finding.get("description"):
          lines.append(f"{finding['description']}\n")
        meta_rows = []
        if finding.get("tool"):
          meta_rows.append(f"| Tool | `{finding['tool']}` |")
        if finding.get("cve"):
          meta_rows.append(f"| CVE | {finding['cve']} |")
        if finding.get("status"):
          meta_rows.append(f"| Status | {finding['status']} |")
        if meta_rows:
          lines.append("| Field | Value |")
          lines.append("|-------|-------|")
          lines += meta_rows
          lines.append("")
        if finding.get("evidence"):
          lines.append("**Evidence:**")
          lines.append("```")
          lines.append(finding["evidence"])
          lines.append("```")
          lines.append("")
        if finding.get("recommendation"):
          lines.append(f"**Recommendation:** {finding['recommendation']}\n")
        if finding.get("tags"):
          lines.append(f"**Tags:** {', '.join(finding['tags'])}\n")
  elif total_findings == 0:
    lines.append("## Findings\n")
    lines.append("*No findings recorded for this session.*\n")

  # Handover history
  if handover_history:
    lines.append("## Handover History\n")
    for h in handover_history:
      ts_str = h.get("timestamp", "")
      category = h.get("category", "unknown")
      confidence = h.get("confidence", 0)
      note = h.get("note", "")
      lines.append(f"- **{ts_str}** — {category} ({int(confidence * 100)}% confidence)")
      if note:
        lines.append(f"  > {note}")
    lines.append("")

  # Notes
  if include_notes:
    notes = session_store.list_notes(session_id)
    if notes:
      lines.append("## Session Notes\n")
      for note_meta in notes:
        note_name = note_meta["filename"]
        note_folder = note_meta.get("folder", "")
        heading = f"{note_folder}/{note_name}" if note_folder else note_name
        content = session_store.load_note(session_id, note_name, note_folder)
        lines.append(f"### {heading}\n")
        if content:
          lines.append(content)
        lines.append("")

  # Event log
  if include_event_log and event_log:
    lines.append("## Activity Timeline\n")
    lines.append("| Time | Event | Message |")
    lines.append("|------|-------|---------|")
    for evt in event_log:
      ts_str = _fmt_ts(evt.get("timestamp", 0))
      evt_type = str(evt.get("type", "")).replace("_", " ").title()
      msg = str(evt.get("message", ""))
      lines.append(f"| {ts_str} | {evt_type} | {msg} |")
    lines.append("")

  return "\n".join(lines)


def _generate_executive_summary(session_data: dict, focus: str = "", tools_run: list | None = None) -> str:
  """Use LLM to generate a concise executive summary."""
  target = session_data.get("target", "unknown")
  objective = session_data.get("objective", "security assessment")
  risk_level = session_data.get("risk_level", "unknown")
  total_findings = session_data.get("total_findings", 0)
  tools = tools_run if tools_run is not None else session_data.get("tools_executed", [])
  findings = session_data.get("findings", [])
  name = session_data.get("name", "")

  # Build findings context
  findings_context = ""
  if findings:
    sev_counts: dict = {}
    for f in findings:
      sev = f.get("severity", "info")
      sev_counts[sev] = sev_counts.get(sev, 0) + 1
    sev_summary = ", ".join(f"{v} {k}" for k, v in sev_counts.items())
    findings_list = "\n".join(
      f"- [{f.get('severity', 'info').upper()}] {f.get('title', 'Unknown')}: {f.get('description', '')[:120]}"
      for f in findings[:10]  # cap at 10 for context window
    )
    findings_context = f"Severity breakdown: {sev_summary}\n\nKey findings:\n{findings_list}"
  else:
    findings_context = "No structured findings were recorded in this session."

  focus_line = f"\nSpecifically focus on: {focus}" if focus else ""

  prompt = f"""You are a professional penetration tester writing an executive summary for a security assessment report.

Session name: {name or target}
Target: {target}
Objective: {objective}
Risk Level: {risk_level.upper()}
Total Findings: {total_findings}
Tools Used: {', '.join(tools[:15]) if tools else 'None recorded'}{focus_line}

Findings:
{findings_context}

Write a concise executive summary (3-5 paragraphs) suitable for a technical audience. Include:
1. An overview of what was tested and the methodology
2. Key findings and their business impact
3. Overall risk assessment and recommended immediate actions
4. A brief remediation priority roadmap

Write in professional security assessment style. Be specific and actionable. Do not use placeholder text."""

  try:
    response = _llm_client.chat([{"role": "user", "content": prompt}], think=True, num_ctx=_llm_client.num_ctx_analyse)
    return str(response).strip()
  except Exception as e:
    logger.error(f"LLM executive summary generation failed: {e}")
    return f"*AI executive summary generation failed: {e}. See findings section for details.*"


def _fmt_ts(ts: int) -> str:
  if not ts:
    return "—"
  try:
    return datetime.utcfromtimestamp(int(ts)).strftime("%Y-%m-%d %H:%M UTC")
  except Exception:
    return str(ts)


def _actual_tools_run(session_id: str, session_data: dict) -> list:
  """
  Return an ordered, deduplicated list of tool names that were actually
  executed for this session, derived from RunHistoryStore.

  Primary match: run_history entries whose session_id matches.
  Fallback heuristic (for entries recorded before session_id tagging):
    entry timestamp >= session created_at AND (tool in planned list OR
    target appears in params).
  Falls back to the planned tools_executed list if no run history exists.
  """
  import json as _json
  from datetime import timezone

  all_logs = _run_history.get_all()
  created_at_ts = int(session_data.get("created_at", 0) or 0)
  target_lower = (session_data.get("target", "") or "").lower()
  planned = session_data.get("tools_executed", [])
  planned_set = {t.lower() for t in planned}
  session_id_clean = (session_id or "").strip()

  matched = []
  for entry in all_logs:
    entry_sid = (entry.get("session_id") or "").strip()
    if session_id_clean and entry_sid:
      if entry_sid == session_id_clean:
        matched.append(entry)
      continue

    # Heuristic fallback for untagged entries
    ts_raw = entry.get("timestamp", "")
    entry_ts = None
    if ts_raw:
      try:
        if isinstance(ts_raw, (int, float)):
          entry_ts = int(ts_raw)
        else:
          dt = datetime.fromisoformat(str(ts_raw).replace("Z", "+00:00"))
          if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
          entry_ts = int(dt.timestamp())
      except (ValueError, TypeError):
        pass

    after_session = (entry_ts is None) or (entry_ts >= created_at_ts)
    tool_match = entry.get("tool", "").lower() in planned_set
    params_str = _json.dumps(entry.get("params", {}), default=str).lower()
    target_match = bool(target_lower) and (target_lower in params_str)

    if after_session and (tool_match or target_match):
      matched.append(entry)

  if not matched:
    # No run history found — fall back to planned list
    return planned

  # Return oldest-first, deduplicated, preserving order
  matched_chrono = list(reversed(matched))
  seen: set = set()
  result = []
  for entry in matched_chrono:
    tool = entry.get("tool", "")
    if tool and tool not in seen:
      seen.add(tool)
      result.append(tool)
  return result
